### ISSUE TITLE
BEP20 Token

### ISSUE THREAD

**Issue by eugjr** [AlgoNetwork/TokenFactory#1]
Hello, it is possible to create a BEP20 token, that runs on BSC Network?

**Comment by AlgoNetwork** [comment]
> Hello, it is possible to create a BEP20 token, that runs on BSC Network?

Sure! your can deploy to any EVM Blockchain, Support Blockchain List:
https://algonetwork.github.io/EVM-Blockchain-Index/

**Comment by danidamiobi** [comment]
How do I set taxes and how much is it to use this tool
? @AlgoNetwork

**Comment by AlgoNetwork** [comment]
> How do I set taxes and how much is it to use this tool ? @AlgoNetwork

Hi,
1. install metamask in your chrome.
2. send some eth/bnb/....  to your metamask account.
3. use our tool.
