### ISSUE TITLE
Etherscan Contract Verification

### ISSUE THREAD

**Issue by chris-iwolf** [AlgoNetwork/TokenFactory#2]
How do I verify the smart contract on explorers?

**Comment by AlgoNetwork** [comment]
Hi, The contract will be automatically verified.

**Comment by ultra-pool** [comment]
> Hi, The contract will be automatically verified.

On BSC it doesn't verify the token and no option to do so from what Iv seen and tested on your demo site.

**Comment by AlgoNetwork** [comment]
> > Hi, The contract will be automatically verified.
> 
> On BSC it doesn't verify the token and no option to do so from what Iv seen and tested on your demo site.

Hi, please show your BSC contract address.

**Comment by ultra-pool** [comment]
> > > Hi, The contract will be automatically verified.
> > 
> > 
> > On BSC it doesn't verify the token and no option to do so from what Iv seen and tested on your demo site.
> 
> Hi, please show your BSC contract address.

https://testnet.bscscan.com/address/0xb2696fab5a66790242770f17878ee498fea4e7f4#code

**Comment by AlgoNetwork** [comment]
> > > > Hi, The contract will be automatically verified.
> > > 
> > > 
> > > On BSC it doesn't verify the token and no option to do so from what Iv seen and tested on your demo site.
> > 
> > 
> > Hi, please show your BSC contract address.
> 
> https://testnet.bscscan.com/address/0xb2696fab5a66790242770f17878ee498fea4e7f4#code
😅
I just forgot to ask, what type of token did you choose?

**Comment by ultra-pool** [comment]
It was the liquidity token. 

Also I wanted to ask if there was a way to setup for collecting a fee before they can submit the contact.

**Comment by AlgoNetwork** [comment]
I can't verify this contract, this token does not appear to be created by Tokenfactory.
and yes, 
await web3.eth.sendTransaction({
      from: web3.currentProvider.selectedAddress,
      to: feeRecieverAddress,
      value: Fee,

  }).then(()=>{
    // submit contract.
})

**Comment by ultra-pool** [comment]
> I can't verify this contract, this token does not appear to be created by Tokenfactory. and yes, await web3.eth.sendTransaction({ from: web3.currentProvider.selectedAddress, to: feeRecieverAddress, value: Fee,
> 
> }).then(()=>{ // submit contract. })

Yes I tested with the testnet. And it wouldnt let me verify this testnet token. Can you put the .sol files into this source so we can also see the contracts.

**Comment by ultra-pool** [comment]
Iv tried adding this code in like 10 different areas of the source. Haven't found the correct spot for it to work. any suggestions?

**Comment by ultra-pool** [comment]
@AlgoNetwork

**Comment by AlgoNetwork** [comment]
Maybe your contract is inconsistent.
