### ISSUE TITLE
not connecting to metamask

### ISSUE THREAD

**Issue by bghad1** [AlgoNetwork/TokenFactory#3]
Hi
Thanks for sharing such a nice tool
I was trying to test the tool, but was not able to connect my metamask wallet to the website.
I even tried eth mainnet and bsc testnet, but none of them got connected to the website
I there any special thing that I'm missing?

**Comment by AlgoNetwork** [comment]
Hi, if you can use Metamask on https://app.sushi.com/swap
then you can also use it on Token Factory.
