### ISSUE TITLE
index.html line 832

### ISSUE THREAD

**Issue by ultra-pool** [AlgoNetwork/TokenFactory#8]
Current error on line 832 on index.html which also break main page. 

Uncaught TypeError: arrLang[lang] is undefined
    <anonymous> https://algonetwork.github.io/TokenFactory/:832
    jQuery 2
        each
        each
    <anonymous> https://algonetwork.github.io/TokenFactory/:832

![image](https://user-images.githubusercontent.com/37985843/184733303-d6b87c11-2242-4c06-8d38-d98308258462.png)

**Comment by AlgoNetwork** [comment]
Fixed,Thank you!
